import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portifolio | Jamilson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <header className="header">
          <div className="profile-picture">
            <img src="" alt="Foto de Perfil" />
          </div>
          <div className="personal-info">
            <h1>Jamilson Ferreira</h1>
            <p>Engenharia de Dados</p>
            <p>dados.jamilson@gmail.com</p>
          </div>
          <div className="academic-info">
            <h2>Formação Acadêmica</h2>
            <p>Estudante de Ciências da Computação</p>
            <p>Universidade Estadual da Paraíba - UEPB</p>
          </div>
        </header>
        <nav className="navbar">
            <ul>
              <li><Link href="/engenharia-de-dados">Engenharia de Dados</Link></li>
              <li><Link href="/machine-learning">Machine Learning</Link></li>
              <li><Link href="/ciencias-de-dados">Ciências de Dados</Link></li>
            </ul>
          </nav>
        {children}
      </body>
    </html>
  );
}
